name: Live test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/live-test.yaml"

jobs:
  test:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run tests (IPv4)
        env:
          PROTO: udp4
          HOSTNAME: ${{ vars.HOSTNAME }}
        run: deno test --allow-net --allow-env test.ts

      - name: Run tests (IPv6)
        env:
          PROTO: udp6
          HOSTNAME: ${{ vars.HOSTNAME }}
        run: deno test --allow-net --allow-env test.ts
