name: Live test

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/live-test.yaml"

jobs:
  test-ipv4:
    runs-on: ubuntu-latest

    env:
      HOSTNAME: udp-echo.nordicsemi.academy

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run tests (IPv4)
        env:
          PROTO: udp4
          HOSTNAME: ${{ env.HOSTNAME }}
        run: deno test --allow-net --allow-env test.ts

  test-ipv6:
    runs-on: ubuntu-latest

    env:
      HOSTNAME: udp-echo.nordicsemi.academy

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Set up WARP
        uses: fscarmen/warp-on-actions@v1.0

      - name: Run tests (IPv6)
        env:
          PROTO: udp6
          HOSTNAME: ${{ env.HOSTNAME }}
        run: deno test --allow-net --allow-env test.ts
